server:
  port: 18189

spring:
  profiles:
    group:
      "default": "datasource,pay"
      "local": "local-datasource,pay"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: info
  com.jpa: debug
